CREATE TABLE [Author](

    [Id] UNIQUEIDENTIFIER NOT NULL,
    [Name] NVARCHAR(80) NOT NULL,
    [Title] NVARCHAR(80) NOT NULL,
    [Image] NVARCHAR(1024) NOT NULL,
    [Bio] NVARCHAR(2000) NOT NULL,
    [Url] NVARCHAR(450) NOT NULL,
    [Email] NVARCHAR(180) NOT NULL,
    [Type] TINYINT NOT NULL,

    CONSTRAINT [PK_Author] PRIMARY KEY ([Id])
)
GO